### ISSUE TITLE
How to access '/' route once started

### ISSUE THREAD

**Issue by 11fishem** [am1tyadav/Image-Classifier-Web-App#1]
All I received when running the script successfully was 

```$ python app.py
Using TensorFlow backend.
Creating Model..
2018-12-30 18:55:42.718794: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Model created..
Loading model weights..
Weights loaded..
```

Then it exited. Thanks!

**Comment by am1tyadav** [comment]
app will expect a folder called 'static' in addition the 'model' folder. did you create it? i'm not sure but it could be the issue

**Comment by 11fishem** [comment]
I just tried with an added static folder, and it still simply exited. Looking through the code, i'm wondering where I am supposed to be able to see the app, I don't see an app.run function anywhere in the code. Is this supposed to be running on localhost and on what port?

**Comment by am1tyadav** [comment]
You should see just one more line after the `Weights loaded..` like this: 
```
Model created..
Loading model weights..
Weights loaded..
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```
To make sure it's still working, I downloaded this repo on another machine just now and these were the steps I followed: https://github.com/am1tyadav/Image-Classifier-Web-App#how-to-use-this-app

**Comment by 11fishem** [comment]
Flask run worked! I was doing python app.py.

**Comment by am1tyadav** [comment]
Great! 😄
